qx2277_hw2_p8105
================
Qiaoen Xia
2026-10-07

``` r
library("tidyverse")
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readr)
```

\#Q1

``` r
NYC_Data <- read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(NYC_Data)
```

    ## # A tibble: 6 × 32
    ##   Division Line     `Station Name` `Station Latitude` `Station Longitude` Route1
    ##   <chr>    <chr>    <chr>                       <dbl>               <dbl> <chr> 
    ## 1 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 2 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 3 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 4 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 5 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 6 BMT      4 Avenue 45th St                      40.6               -74.0 R     
    ## # ℹ 26 more variables: Route2 <chr>, Route3 <chr>, Route4 <chr>, Route5 <chr>,
    ## #   Route6 <chr>, Route7 <chr>, Route8 <dbl>, Route9 <dbl>, Route10 <dbl>,
    ## #   Route11 <dbl>, `Entrance Type` <chr>, Entry <chr>, `Exit Only` <chr>,
    ## #   Vending <chr>, Staffing <chr>, `Staff Hours` <chr>, ADA <lgl>,
    ## #   `ADA Notes` <chr>, `Free Crossover` <lgl>, `North South Street` <chr>,
    ## #   `East West Street` <chr>, Corner <chr>, `Entrance Latitude` <dbl>,
    ## #   `Entrance Longitude` <dbl>, `Station Location` <chr>, …

``` r
variable.names(NYC_Data)
```

    ##  [1] "Division"           "Line"               "Station Name"      
    ##  [4] "Station Latitude"   "Station Longitude"  "Route1"            
    ##  [7] "Route2"             "Route3"             "Route4"            
    ## [10] "Route5"             "Route6"             "Route7"            
    ## [13] "Route8"             "Route9"             "Route10"           
    ## [16] "Route11"            "Entrance Type"      "Entry"             
    ## [19] "Exit Only"          "Vending"            "Staffing"          
    ## [22] "Staff Hours"        "ADA"                "ADA Notes"         
    ## [25] "Free Crossover"     "North South Street" "East West Street"  
    ## [28] "Corner"             "Entrance Latitude"  "Entrance Longitude"
    ## [31] "Station Location"   "Entrance Location"

``` r
head(NYC_Data)
```

    ## # A tibble: 6 × 32
    ##   Division Line     `Station Name` `Station Latitude` `Station Longitude` Route1
    ##   <chr>    <chr>    <chr>                       <dbl>               <dbl> <chr> 
    ## 1 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 2 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 3 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 4 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 5 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 6 BMT      4 Avenue 45th St                      40.6               -74.0 R     
    ## # ℹ 26 more variables: Route2 <chr>, Route3 <chr>, Route4 <chr>, Route5 <chr>,
    ## #   Route6 <chr>, Route7 <chr>, Route8 <dbl>, Route9 <dbl>, Route10 <dbl>,
    ## #   Route11 <dbl>, `Entrance Type` <chr>, Entry <chr>, `Exit Only` <chr>,
    ## #   Vending <chr>, Staffing <chr>, `Staff Hours` <chr>, ADA <lgl>,
    ## #   `ADA Notes` <chr>, `Free Crossover` <lgl>, `North South Street` <chr>,
    ## #   `East West Street` <chr>, Corner <chr>, `Entrance Latitude` <dbl>,
    ## #   `Entrance Longitude` <dbl>, `Station Location` <chr>, …

``` r
NYC_clean = NYC_Data |>
  select(
    line = Line,
    station_name = `Station Name`,
    station_latitude = `Station Latitude`,
    station_longitude = `Station Longitude`,
    route1 = Route1,
    route2 = Route2,
    route3 = Route3,
    route4 = Route4,
    route5 = Route5,
    route6 = Route6,
    route7 = Route7,
    route8 = Route8,
    route9 = Route9,
    route10 = Route10,
    route11 = Route11,
    entry = Entry,
    vending = Vending,
    entrance_type = `Entrance Type`,
    ada = ADA
  ) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
glimpse(NYC_clean)
```

    ## Rows: 1,868
    ## Columns: 19
    ## $ line              <chr> "4 Avenue", "4 Avenue", "4 Avenue", "4 Avenue", "4 A…
    ## $ station_name      <chr> "25th St", "25th St", "36th St", "36th St", "36th St…
    ## $ station_latitude  <dbl> 40.66040, 40.66040, 40.65514, 40.65514, 40.65514, 40…
    ## $ station_longitude <dbl> -73.99809, -73.99809, -74.00355, -74.00355, -74.0035…
    ## $ route1            <chr> "R", "R", "N", "N", "N", "R", "R", "R", "R", "R", "R…
    ## $ route2            <chr> NA, NA, "R", "R", "R", NA, NA, NA, NA, NA, NA, NA, N…
    ## $ route3            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route4            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route5            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route6            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route7            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route8            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route9            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route10           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route11           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ entry             <lgl> TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…
    ## $ vending           <chr> "YES", "YES", "YES", "YES", "YES", "YES", "YES", "YE…
    ## $ entrance_type     <chr> "Stair", "Stair", "Stair", "Stair", "Stair", "Stair"…
    ## $ ada               <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…

``` r
dim(NYC_clean)
```

    ## [1] 1868   19

``` r
class(NYC_clean$entry)
```

    ## [1] "logical"

``` r
sum(duplicated(NYC_clean)) #1184
```

    ## [1] 1184

``` r
duplicate_rows = NYC_clean[
  duplicated(NYC_clean) |
    duplicated(NYC_clean, fromLast = TRUE),
]

#View(duplicate_rows)#1641



#- 1,641 rows: all records belonging to repeated groups, including the first occurrence in each group.
#- 1,184 rows: additional records after the first occurrence in each group.
#- 1,641 − 1,184 = 457: 457 distinct row combinations appeared more than once.
#- 1,868 − 1,641 = 227: 227 distinct row combinations appeared exactly once.


row_counts = count(
  NYC_clean,
  across(everything()),
  name = "n_copies",
  sort = TRUE
)


repeated_groups = filter(row_counts, n_copies > 1)

head(repeated_groups)#showing how many copies in the last column
```

    ## # A tibble: 6 × 20
    ##   line      station_name station_latitude station_longitude route1 route2 route3
    ##   <chr>     <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ## 1 8 Avenue  34th St                  40.8             -74.0 A      C      E     
    ## 2 Queens B… Jamaica-179…             40.7             -73.8 F      <NA>   <NA>  
    ## 3 6 Avenue  14th St                  40.7             -74.0 F      L      M     
    ## 4 6 Avenue  47-50th Sts…             40.8             -74.0 B      D      F     
    ## 5 8 Avenue  23rd St                  40.7             -74.0 C      E      <NA>  
    ## 6 Fulton    Lafayette Av             40.7             -74.0 C      <NA>   <NA>  
    ## # ℹ 13 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>, n_copies <int>

The dataset contains information on NYC subway entrances and exits,
including subway line, station name and coordinates, routes served,
entry permission, vending availability, entrance type, and ADA
compliance. I retained these variables, manually renamed the columns,
and converted entry from “YES”/“NO” to a logical variable. The resulting
dataset contains 1,868 rows and 19 columns. I examined repeated row
combinations and found 684 distinct combinations: 227 appeared once,
while 457 appeared multiple times, accounting for 1,641 records and
1,184 additional copies beyond the first occurrence. I created an
n_copies variable to examine these frequencies and used distinct() to
create a separate dataset containing 684 rows and 19 columns.

``` r
NYC_unique = distinct(NYC_clean)


dim(NYC_unique)
```

    ## [1] 684  19

``` r
NYC_stations = distinct(
  NYC_unique,
  line,
  station_name
)

nrow(NYC_stations)
```

    ## [1] 465

``` r
table(NYC_unique$ada, useNA = "ifany")
```

    ## 
    ## FALSE  TRUE 
    ##   505   179

``` r
ADA_records = filter(NYC_unique, ada == TRUE)

ADA_stations = distinct(
  ADA_records,
  line,
  station_name
)

nrow(ADA_stations)
```

    ## [1] 84

\#Q2

``` r
library(readxl)

Mr_Trash_Wheel_dat <- read_excel("data/202610 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
head(Mr_Trash_Wheel_dat)
```

    ## # A tibble: 6 × 16
    ##   Dumpster Month Year  Date                `Weight (tons)`
    ##      <dbl> <chr> <chr> <dttm>                        <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00            4.31
    ## 2        2 May   2014  2014-05-16 00:00:00            2.74
    ## 3        3 May   2014  2014-05-16 00:00:00            3.45
    ## 4        4 May   2014  2014-05-17 00:00:00            3.1 
    ## 5        5 May   2014  2014-05-17 00:00:00            4.06
    ## 6        6 May   2014  2014-05-20 00:00:00            2.71
    ## # ℹ 11 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Sports Balls` <dbl>,
    ## #   `Homes Powered*` <dbl>, ...15 <lgl>, ...16 <lgl>

``` r
Mr_Trash_Wheel_clean = Mr_Trash_Wheel_dat[, 1:14]

Mr_Trash_Wheel_clean = Mr_Trash_Wheel_clean[
  -nrow(Mr_Trash_Wheel_clean),
]


dim(Mr_Trash_Wheel_clean)
```

    ## [1] 740  14

``` r
tail(Mr_Trash_Wheel_clean)
```

    ## # A tibble: 6 × 14
    ##   Dumpster Month Year  Date                `Weight (tons)`
    ##      <dbl> <chr> <chr> <dttm>                        <dbl>
    ## 1      735 May   2026  2026-05-26 00:00:00            2.12
    ## 2      736 May   2026  2026-05-26 00:00:00            3.27
    ## 3      737 May   2026  2026-05-29 00:00:00            2.94
    ## 4      738 June  2026  2026-06-15 00:00:00            3.8 
    ## 5      739 June  2026  2026-06-18 00:00:00            3.73
    ## 6      740 June  2026  2026-06-26 00:00:00            2.48
    ## # ℹ 9 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Sports Balls` <dbl>,
    ## #   `Homes Powered*` <dbl>

``` r
names(Mr_Trash_Wheel_clean) = c(
  "dumpster",
  "month",
  "year",
  "date",
  "weight_tons",
  "volume_cubic_yards",
  "plastic_bottles",
  "polystyrene",
  "cigarette_butts",
  "glass_bottles",
  "plastic_bags",
  "wrappers",
  "sports_balls",
  "homes_powered"
)

names(Mr_Trash_Wheel_clean)
```

    ##  [1] "dumpster"           "month"              "year"              
    ##  [4] "date"               "weight_tons"        "volume_cubic_yards"
    ##  [7] "plastic_bottles"    "polystyrene"        "cigarette_butts"   
    ## [10] "glass_bottles"      "plastic_bags"       "wrappers"          
    ## [13] "sports_balls"       "homes_powered"

``` r
Mr_Trash_Wheel_clean$sports_balls = as.integer(
  round(Mr_Trash_Wheel_clean$sports_balls)
  
)

head(Mr_Trash_Wheel_clean)
```

    ## # A tibble: 6 × 14
    ##   dumpster month year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ## 2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ## 3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ## 4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ## 5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ## 6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

``` r
Professor_Trash_Wheel_dat <- read_excel("data/202610 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel")

Professor_Trash_Wheel_clean = Professor_Trash_Wheel_dat[
  -nrow(Professor_Trash_Wheel_dat),
]

tail(Professor_Trash_Wheel_clean)
```

    ## # A tibble: 6 × 13
    ##   Dumpster Month      Year Date                `Weight (tons)`
    ##      <dbl> <chr>     <dbl> <dttm>                        <dbl>
    ## 1      132 July       2025 2025-07-16 00:00:00            2.38
    ## 2      133 August     2025 2025-08-04 00:00:00            2.6 
    ## 3      134 September  2025 2025-09-26 00:00:00            3.19
    ## 4      135 November   2025 2025-11-13 00:00:00            1.55
    ## 5      136 February   2026 2026-02-26 00:00:00            3.01
    ## 6      137 March      2026 2026-03-09 00:00:00            2.35
    ## # ℹ 8 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <chr>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Homes Powered*` <dbl>

``` r
variable.names(Professor_Trash_Wheel_clean)
```

    ##  [1] "Dumpster"             "Month"                "Year"                
    ##  [4] "Date"                 "Weight (tons)"        "Volume (cubic yards)"
    ##  [7] "Plastic Bottles"      "Polystyrene"          "Cigarette Butts"     
    ## [10] "Glass Bottles"        "Plastic Bags"         "Wrappers"            
    ## [13] "Homes Powered*"

``` r
names(Professor_Trash_Wheel_clean) = c(
  "dumpster",
  "month",
  "year",
  "date",
  "weight_tons",
  "volume_cubic_yards",
  "plastic_bottles",
  "polystyrene",
  "cigarette_butts",
  "glass_bottles",
  "plastic_bags",
  "wrappers",
  "homes_powered"
)

Professor_Trash_Wheel_clean$plastic_bottles = as.numeric(
  Professor_Trash_Wheel_clean$plastic_bottles
)
```

    ## Warning: NAs introduced by coercion

``` r
class(Professor_Trash_Wheel_clean$plastic_bottles)
```

    ## [1] "numeric"

``` r
Gwynnda_dat <- read_excel("data/202610 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda the Good Wheel of the W")
head(Gwynnda_dat)
```

    ## # A tibble: 6 × 12
    ##   Dumpster Month   Year Date                `Weight (tons)`
    ##      <dbl> <chr>  <dbl> <dttm>                        <dbl>
    ## 1        1 July    2021 2021-07-03 00:00:00            0.93
    ## 2        2 July    2021 2021-07-07 00:00:00            2.26
    ## 3        3 July    2021 2021-07-07 00:00:00            1.62
    ## 4        4 July    2021 2021-07-16 00:00:00            1.76
    ## 5        5 July    2021 2021-07-30 00:00:00            1.53
    ## 6        6 August  2021 2021-08-11 00:00:00            2.06
    ## # ℹ 7 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Plastic Bags` <dbl>,
    ## #   Wrappers <dbl>, `Homes Powered*` <dbl>

``` r
Gwynnda_clean = filter(
  Gwynnda_dat,
  !is.na(Dumpster)
)

tail(Gwynnda_clean)
```

    ## # A tibble: 6 × 12
    ##   Dumpster Month  Year Date                `Weight (tons)`
    ##      <dbl> <chr> <dbl> <dttm>                        <dbl>
    ## 1      393 May    2026 2026-05-28 00:00:00            3.38
    ## 2      394 May    2026 2026-05-28 00:00:00            2.91
    ## 3      395 May    2026 2026-05-28 00:00:00            3.34
    ## 4      396 May    2026 2026-05-29 00:00:00            3.62
    ## 5      397 June   2026 2026-06-12 00:00:00            3.63
    ## 6      398 June   2026 2026-06-20 00:00:00            2.79
    ## # ℹ 7 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Plastic Bags` <dbl>,
    ## #   Wrappers <dbl>, `Homes Powered*` <dbl>

``` r
dim(Gwynnda_clean)
```

    ## [1] 392  12

``` r
variable.names(Gwynnda_clean)
```

    ##  [1] "Dumpster"             "Month"                "Year"                
    ##  [4] "Date"                 "Weight (tons)"        "Volume (cubic yards)"
    ##  [7] "Plastic Bottles"      "Polystyrene"          "Cigarette Butts"     
    ## [10] "Plastic Bags"         "Wrappers"             "Homes Powered*"

``` r
names(Gwynnda_clean) = c(
  "dumpster",
  "month",
  "year",
  "date",
  "weight_tons",
  "volume_cubic_yards",
  "plastic_bottles",
  "polystyrene",
  "cigarette_butts",
  "plastic_bags",
  "wrappers",
  "homes_powered"
)
```

``` r
sum(duplicated(Mr_Trash_Wheel_clean))
```

    ## [1] 0

``` r
sum(duplicated(Professor_Trash_Wheel_clean))
```

    ## [1] 0

``` r
sum(duplicated(Gwynnda_clean))
```

    ## [1] 0

``` r
Mr_Trash_Wheel_clean$trash_wheel = "Mr. Trash Wheel"
Professor_Trash_Wheel_clean$trash_wheel = "Professor Trash Wheel"
Gwynnda_clean$trash_wheel = "Gwynnda"
```

``` r
Mr_Trash_Wheel_clean$trash_wheel = "Mr. Trash Wheel"
Professor_Trash_Wheel_clean$trash_wheel = "Professor Trash Wheel"
Gwynnda_clean$trash_wheel = "Gwynnda"

Mr_Trash_Wheel_clean$year = as.numeric(
  Mr_Trash_Wheel_clean$year
)#previously class char

class(Mr_Trash_Wheel_clean$year)
```

    ## [1] "numeric"

``` r
trash_wheel_combined = bind_rows(
  Mr_Trash_Wheel_clean,
  Professor_Trash_Wheel_clean,
  Gwynnda_clean
)

dim(trash_wheel_combined)
```

    ## [1] 1269   15

``` r
professor_data = filter(
  trash_wheel_combined,
  trash_wheel == "Professor Trash Wheel"
)

professor_total_weight = sum(
  professor_data$weight_tons,
  na.rm = TRUE
)

gwynnda_june_2022 = filter(
  trash_wheel_combined,
  trash_wheel == "Gwynnda",
  year == 2022,
  month == "June"
)

gwynnda_total_cigarettes = sum(
  gwynnda_june_2022$cigarette_butts,
  na.rm = TRUE
)




professor_total_weight
```

    ## [1] 294.96

``` r
gwynnda_total_cigarettes
```

    ## [1] 18120

The combined Trash Wheel dataset contains 1188 observations and 15
variables. Each observation represents a dumpster collection record from
Mr. Trash Wheel, Professor Trash Wheel, or Gwynnda. Key variables
include collection date, trash weight in tons, volume in cubic yards,
and counts of items such as plastic bottles, cigarette butts, and
wrappers. I removed non-data entries, mostly last row, standardized
variable names, converted year to a consistent numeric type, and rounded
sports ball counts to integers. for Professor trash, I converted the
class of the variable plastic_bottles to numeric.I added a trash wheel
identifier before combining the datasets; variables unavailable for a
particular trash wheel were filled with NA. Based on available data,
Professor Trash Wheel collected 282.26 tons of trash, and Gwynnda
collected 18120 cigarette butts in June 2022.

\#Q3

``` r
mci_amyloid <- read_csv("data/mci_amyloid.csv", skip = 1, na = c("", "NA", "Na", "na", "N/A", "."))
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(mci_amyloid)
```

    ## # A tibble: 6 × 6
    ##   `Study ID` Baseline `Time 2` `Time 4` `Time 6` `Time 8`
    ##        <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>
    ## 1          1    0.111   NA        0.109    0.105    0.107
    ## 2          2    0.107    0.109    0.109    0.106    0.107
    ## 3          3    0.106    0.109    0.106   NA        0.106
    ## 4          4    0.109    0.109    0.111    0.107    0.111
    ## 5          5    0.108    0.112    0.115    0.107    0.106
    ## 6          6    0.112    0.113    0.111    0.110    0.115

``` r
MCI_baseline = read_csv(
  "data/MCI_baseline.csv",
  skip = 1, na = c("", "NA", "Na", "na", "N/A", ".")
)
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
variable.names(mci_amyloid)
```

    ## [1] "Study ID" "Baseline" "Time 2"   "Time 4"   "Time 6"   "Time 8"

``` r
variable.names(MCI_baseline)
```

    ## [1] "ID"           "Current Age"  "Sex"          "Education"    "apoe4"       
    ## [6] "Age at onset"

``` r
names(MCI_baseline) = c(
  "id",
  "baseline_age",
  "sex",
  "education",
  "apoe4",
  "mci_onset_age"
)



MCI_baseline$sex = factor(
  MCI_baseline$sex,
  levels = c(0, 1),
  labels = c("Female", "Male")
)

MCI_baseline$apoe4 = factor(
  MCI_baseline$apoe4,
  levels = c(0, 1),
  labels = c("Non-carrier", "Carrier")
)
```

``` r
MCI_baseline$mci_onset_age = as.numeric(
  MCI_baseline$mci_onset_age
)

MCI_baseline_clean = filter(
  MCI_baseline,
  is.na(mci_onset_age) | mci_onset_age > baseline_age
)

nrow(MCI_baseline_clean)
```

    ## [1] 479

``` r
MCI_developed = filter(
  MCI_baseline,
  !is.na(mci_onset_age) & mci_onset_age > baseline_age
)

nrow(MCI_developed)
```

    ## [1] 93

``` r
average_baseline_age = mean(
  MCI_baseline_clean$baseline_age,
  na.rm = TRUE
)

average_baseline_age
```

    ## [1] 65.0286

``` r
women = filter(
  MCI_baseline_clean,
  sex == "Female"
)

table(women$apoe4, useNA = "ifany")
```

    ## 
    ## Non-carrier     Carrier 
    ##         147          63

``` r
prop_women_carriers = mean(
  women$apoe4 == "Carrier",
  na.rm = TRUE
)

prop_women_carriers
```

    ## [1] 0.3

I imported the baseline dataset using skip = 1 to omit the initial
description row and specified missing-value codes, including “.”. I
standardized variable names and converted sex and APOE4 carrier status
to factors with descriptive labels. I excluded participants whose MCI
onset age was less than or equal to their baseline age, while retaining
participants with missing onset ages because they remained MCI-free
during follow-up. The original dataset contained 483 participants, of
whom 479 met the inclusion criteria. Each row in the cleaned dataset
represents one participant, with variables for participant ID, baseline
age, sex, education, APOE4 status, and MCI onset age. Among eligible
participants, 79 developed MCI during follow-up.

``` r
names(mci_amyloid) = c(
  "id",
  "time_0",
  "time_2",
  "time_4",
  "time_6",
  "time_8"
)

names(mci_amyloid)
```

    ## [1] "id"     "time_0" "time_2" "time_4" "time_6" "time_8"

I imported the amyloid dataset by skipping the initial description row
and specifying missing-value codes so that entries such as “NA” and “Na”
were treated consistently. I renamed the columns to identify participant
ID and measurement times. The dataset contains 487 participants, with
amyloid 42/40 ratios recorded at baseline and at 2, 4, 6, and 8 years.
The original structure was wide, with one row per participant and
separate columns for each measurement time. I used pivot_longer() to
reshape the matched data into a tidy long format, with separate
variables for time and amyloid ratio, and converted time to numeric.
Each row in the resulting dataset represents one participant at one
scheduled measurement time. Missing biomarker values were retained.

``` r
baseline_ids = unique(MCI_baseline_clean$id)
amyloid_ids = unique(mci_amyloid$id)


baseline_only = setdiff(baseline_ids, amyloid_ids)


amyloid_only = setdiff(amyloid_ids, baseline_ids)

baseline_only
```

    ## [1]  14  49  92 179 268 304 389 412

``` r
amyloid_only
```

    ##  [1]  72 234 283 380 484 485 486 487 488 489 490 491 492 493 494 495

``` r
length(baseline_only)
```

    ## [1] 8

``` r
length(amyloid_only)
```

    ## [1] 16

Eight participants appear only in the cleaned baseline dataset, while 16
appear only in the amyloid dataset. Thus, the participant IDs do not
completely overlap.

``` r
mci_combined = inner_join(
  MCI_baseline_clean,
  mci_amyloid,
  by = "id"
)




mci_combined = pivot_longer(
  mci_combined,
  cols = starts_with("time_"),
  names_to = "time",
  names_prefix = "time_",
  values_to = "amyloid_ratio"
)
mci_combined$time = as.numeric(mci_combined$time)

head(mci_combined)
```

    ## # A tibble: 6 × 8
    ##      id baseline_age sex    education apoe4   mci_onset_age  time amyloid_ratio
    ##   <dbl>        <dbl> <fct>      <dbl> <fct>           <dbl> <dbl>         <dbl>
    ## 1     1         63.1 Female        16 Carrier            NA     0         0.111
    ## 2     1         63.1 Female        16 Carrier            NA     2        NA    
    ## 3     1         63.1 Female        16 Carrier            NA     4         0.109
    ## 4     1         63.1 Female        16 Carrier            NA     6         0.105
    ## 5     1         63.1 Female        16 Carrier            NA     8         0.107
    ## 6     2         65.6 Female        20 Carrier            NA     0         0.107

``` r
dim(mci_combined)
```

    ## [1] 2355    8

``` r
write_csv(
  mci_combined,
  "data/mci_combined.csv")
```
